config/routes.rb
FamilyMe::Application.routes.draw do

  scope "(:locale)", locale: /en|fr/ do
    devise_for :users, :controllers => {
      :sessions => 'sessions',
      :registrations => 'registrations',
      :omniauth_callbacks => "users/omniauth_callbacks"
    }

    match '/icalendar' => 'families#icalendar', as: 'icalendar_events'

    resource :family, only: [:show, :create, :update, :new]
    resources :users, only: [:index]
    resources :invitations, only: [:index, :new, :create] do
      member do
        get 'accept'
        get 'reject'
      end
    end

    root :to => 'families#landing'
  end

  match '/posts' => 'families#show', :as => :dashboard, disable_redirect: true
  match '/posts/*page' => 'families#show', disable_redirect: true

  match '/todos' => 'families#show', disable_redirect: true
  match '/todos/*page' => 'families#show', disable_redirect: true

  match '/positions' => 'families#show', disable_redirect: true
  match '/positions/*page' => 'families#show', disable_redirect: true

  match '/events' => 'families#show', disable_redirect: true
  match '/events/*page' => 'families#show', disable_redirect: true

  namespace :api, constraints: { format: 'json' } do
    namespace :v1 do
      resource :family, only: :show
      resources :users, only: :index
      resources :positions, only: [:create, :index] do
        collection do
          get 'latest'
        end
      end
      resources :posts, only: [:create, :destroy, :index, :show, :update]

      resources :invitations, only: [:create, :index] do
        collection do
          get 'received'
        end
        member do
          get 'accept'
          get 'reject'
        end
      end

      resources :task_lists, only: [:create, :update, :destroy, :show, :index] do
        resources :tasks, only: [:create, :update, :destroy, :show, :index] do
          member do
            get 'finish'
          end
        end
      end

      resources :events, only: [:create, :destroy, :index, :show, :update] do
        collection do
          get 'currents' # list currents and futures
        end
      end
    end
  end

end

app/views/layouts/_messages.html.haml
- flash.each do |name, msg|  
  %div{:class => "alert alert-#{name == :notice ? "success" : "error"}"}
    %a.close{"data-dismiss" => "alert"} ×
    = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navigation.html.haml
.navbar.navbar-inverse
  .navbar-header
    = link_to "FamilyMe", dashboard_path(locale: I18n.locale), :class => 'navbar-brand'
  %ul.nav.navbar-nav.languages
    %li= link_to 'English', url_for(locale: 'en'), class: "#{'selected' if I18n.locale.to_s == 'en'}"
    %li= link_to 'Français', url_for(locale: 'fr'), class: "#{'selected' if I18n.locale.to_s == 'fr'}"

  - if user_signed_in?
    %ul.nav.navbar-nav.navbar-right
      %li= link_to t('webapp.title_1'), users_path
      %li= link_to t('webapp.title_2'), edit_user_registration_path
      %li.dropdown
        %a.dropdown-toggle{'data-toggle' => "dropdown", 'data-target' => '#'}
          = t('webapp.title_3')
          %b.caret.orange-caret
        %ul.dropdown-menu
          %li= link_to t('webapp.title_4'), invitations_path
          %li= link_to t('webapp.title_5'), new_invitation_path
      %li= link_to(t('webapp.title_6'), destroy_user_session_path, method: 'delete')

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:charset => "utf-8"}
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1, maximum-scale=1"}
    %title= content_for?(:title) ? yield(:title) : "FamilyMe"
    %meta{:content => "", :name => "description"}
    %meta{:content => "", :name => "author"}
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
    = yield(:head)
  %body{"data-test-mode" => Rails.env.test?}
    %header= render 'layouts/navigation'

    #main.container{:role => "main"}
      = render 'layouts/messages'

      = yield

app/views/layouts/landing.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>familyMe</title>

  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="">
  <meta name="author" content="familyMe Team">

  <link href="http://netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css" rel="stylesheet">

  <%= stylesheet_link_tag "landing", :media => "all" %>
  <%= csrf_meta_tags %>

</head>
<body>
  <div id="content">

    <header id="main-nav" class="fixed">
      <div class="grid clearfix">
        <%= image_tag("landing/brand-id.png", :class => "brand-id left", :size => "35x35") %>
        <h3 class="brand"> FAMILYME </h3>
        <ul class="navi">
          <li> <h4><a href="#features"><%= t('homepage.header.title_1') %></a></h4> </li>
        </ul>
        <%= link_to t('sign_in'), new_user_session_path, :class => "btn gray-bg button" %>
      </div>
    </header>

    <section id="mission" class="orange-bg">
      <div id="purpose" class="grid clearfix">
        <div class="macintosh"></div>
        <div class="wrapper right">
          <h1><%= t('homepage.call_to_action.title') %></h1>
          <h5><%= t('homepage.call_to_action.description') %> </h5>

          <div class="center">
            <a class="btn btn-default btn-lg btn-success" href="/users/sign_up"><%= t('sign_up') %></a>
          </div>
        </div>
      </div>
    </section>

    <section id="features" class="pale-bg">
      <div class="grid">
        <ul class="navi">
          <li>
            <span class="entypo-social twitter icon-social-twitter" style="font-size: 50px"></span>
            <h4><a href="#features"><%= t('homepage.feature_1') %></a></h4>
          </li>
          <li>
            <span class="entypo calendar icon-calendar" style="font-size: 50px"></span>
            <h4><a href="#archi"><%= t('homepage.feature_2') %></a></h4>
          </li>
          <li>
            <span class="entypo location icon-location" style="font-size: 50px"></span>
            <h4><a href="#archi"><%= t('homepage.feature_3') %></a></h4>
          </li>
          <li>
            <span class="entypo numbered-list icon-numbered-list" style="font-size: 50px"></span>
            <h4><a href="#archi"><%= t('homepage.feature_4') %></a></h4>
          </li>
        </ul>

        <div class="h-wrap">
          <h1><%= t('homepage.subtitle') %></h1>
          <h5><%= t('homepage.subtitle_2') %></h5>
        </div>
      </div>
    </section>

    <section id="eip" class="blue-bg">
      <div></div>
      <div class="grid clearfix">
        <p class="left">
          <%= t('homepage.eip') %>
        </p>
        <h1 class="right"> <strong> { E.I.P } </strong> </h1>
      </div>
    </section>

    <section id="twitter" class="pale-bg">
      <div></div>
      <div class="grid clearfix">
        <h1 class="left"> <img style="margin-top: 35px" width="164px" src="https://g.twimg.com/Twitter_logo_blue.png" /> </h1>
        <p class="right">
          <a class="twitter-timeline" href="https://twitter.com/familyMeEIP" data-widget-id="423996743055712256" data-tweet-limit="1">Tweets by @familyMeEIP</a>
          <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';
          if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
        </p>
      </div>
    </section>

    <section id="features" class="gray-bg" style="padding-top: 100px">
      <div class="grid" style="max-width:none">
        <ul id="members" class="navi" style="width: auto">
          <li>
            <%= image_tag("landing/circla_c.jpg", :class => "circular center", :size => "100x100") %>
            <h4><a href="#features">Charles Circlaeys</a></h4>
          </li>
          <li>
            <%= image_tag("landing/jorge_d.jpg", :class => "circular center", :size => "100x100") %>
            <h4><a href="#archi">Dimitri Jorge</a></h4>
          </li>
          <li>
            <%= image_tag("landing/di-mar_j.jpg", :class => "circular center", :size => "100x100") %>
            <h4><a href="#archi">Julien Di Marco</a></h4>
          </li>
          <li>
            <%= image_tag("landing/rodrig_d.jpg", :class => "circular center", :size => "100x100") %>
            <h4><a href="#archi">Jose Rodrigues</a></h4>
          </li>
          <li>
            <%= image_tag("landing/berhau_n.jpg", :class => "circular center", :size => "100x100") %>
            <h4><a href="#archi">Nicolas Berhault</a></h4>
          </li>
          <li>
            <%= image_tag("landing/serraj_y.jpg", :class => "circular center", :size => "100x100") %>
            <h4><a href="#archi">Younes Seraj</a></h4>
          </li>
        </ul>
      </div>
    </section>

      <footer id="footer">
        <div class="languages">
          <%= link_to 'English', url_for(locale: 'en'), class: "#{'selected' if I18n.locale.to_s == 'en'}" %>
          <%= link_to 'Français', url_for(locale: 'fr'), class: "#{'selected' if I18n.locale.to_s == 'fr'}" %>
        </div>
        <div class="grid clearfix logos">
          <%= image_tag("landing/logo_eip.png", :size => "127x65") %>
          <%= image_tag("landing/brand-id.png", :class => "brand-id", :size => "65x65") %>
          <%= image_tag("landing/logo_epitech.png", :size => "179x65") %>
        </div>
      </footer>

  </div> <!-- /content -->
</body>
</html>